CREATE TABLE users(u_id NUMBER,u_name VARCHAR2(50));
INSERT INTO users(u_name,u_id) VALUES('Alice',1);
INSERT INTO users(u_name,u_id) VALUES('Bob',2);
DESC users;
ALTER TABLE users ADD email VARCHAR2(50);
ALTER TABLE users ADD(age NUMBER,gender VARCHAR2(50));
SELECT * FROM users;
DESC users;
ALTER TABLE users MODIFY (u_name VARCHAR2(100));
SELECT * FROM users;
DESC users;
ALTER TABLE users RENAME COLUMN email TO mail;
DESC users;
ALTER TABLE users DROP COLUMN mail;
DESC users;
ALTER TABLE users DROP(age,gender);
DESC users;
RENAME users TO user_data;
DESC user_data;
